Update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,20 +18,23 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      # Add parameter here
+      ID:
+        type: string
+        default: None   
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl --insecure https://kvdb.io/NH6obrpTfsArn281rBkSLK/migration_<< parameters.ID >>)
+            echo $SUCCESS
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
             fi
 
 jobs:
@@ -165,8 +168,8 @@ jobs:
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
               --tags project=uda-people-backend \
-              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:10}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:10}"  
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}"  
 
       - run:
           name: Ensure front-end infrastructure exist
@@ -174,8 +177,8 @@ jobs:
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
               --tags project=uda-people-frontend \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:10}" \
-              --parameter-overrides ID=""${CIRCLE_WORKFLOW_ID:0:10}""  
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:8}" \
+              --parameter-overrides ID=""${CIRCLE_WORKFLOW_ID:0:8}""  
               
       - run:
           name: Add back-end ip to ansible inventory
@@ -190,9 +193,9 @@ jobs:
             - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure
       - destroy-environment:
-          ID: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:10}
+          ID: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8}
       - destroy-environment:
-          ID: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:10}
+          ID: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:8}
 
   configure-infrastructure:
     docker:
@@ -217,6 +220,7 @@ jobs:
           command: |
             # Your code here
             apk add --update ansible
+            pip install awscli
             # exit 1
       - run:
           name: Configure server
@@ -227,28 +231,60 @@ jobs:
             # exit 1
       # Here's where you will add some code to rollback on failure
       - destroy-environment:
-          ID: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:10}
+          ID: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8}
       - destroy-environment:
-          ID: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:10}
+          ID: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:8}
+
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            # exit 1
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            # Your code here
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              # If you are using kvdb.io, generate the bucket ID "NH6obrpTfsArn281rBkSLK" in your local terminal first
+              curl https://kvdb.io/NH6obrpTfsArn281rBkSLK/migration_${CIRCLE_WORKFLOW_ID:0:8}  -d '1'
+            fi
+            exit 1
+     # Here's where you will add some code to rollback on failure
+     - revert-migrations:
+          ID: ${CIRCLE_WORKFLOW_ID:0:8}
 
 workflows:
   default:
     jobs:
-       - build-frontend
-       - build-backend
-       - test-frontend:
-           requires: [build-frontend]
-       - test-backend:
-           requires: [build-backend]
-       - scan-frontend:
-           requires: [build-frontend]
-       - scan-backend:
-           requires: [build-backend]
-       - deploy-infrastructure:
-           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-           filters:
-             branches:
-               only: [master]
-       - configure-infrastructure:
-           requires: [deploy-infrastructure]
-      
+      - build-frontend
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - scan-backend:
+          requires: [build-backend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [master]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]      
